#测试环境
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: micro-business-A-api
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181,127.0.0.2:2181,127.0.0.3:2181
      enabled: true
      discovery:
        instance-host: ${spring.cloud.client.ip-address}