#测试环境
server:
  port: 8002
  servlet:
    context-path: /micro-business-B-api
spring:
  profiles:
    active: test
  application:
    name: micro-business-B-api
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181,127.0.0.2:2181,127.0.0.3:2181
      enabled: true
      discovery:
        instance-host: ${spring.cloud.client.ip-address}
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
        test:
          url: jdbc:mysql://127.0.0.2:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
  redis:
    #Redis服务器地址
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.2:6379,127.0.0.3:6379
    #Redis服务器连接密码（默认为空)
    password: NuXSy2zTcb1t
    lettuce:
      pool:
        #连接池中的最小空闲连接
        min-idle: 0
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl