#本地环境
nacos:
  namespace: 96a25e9d-6010-42ff-8464-ab061314f74d
  server-addr: 127.0.0.1:8848
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: micro-business-B-api
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}