# micro-service-bss Common Config
################################ spring config start ###############################
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    charset: UTF-8
    location: classpath:config/banner.txt

# 当前项目maven激活环境，例如：local/dev/test，对应pom.xml中profile设置值
---
spring:
  profiles:
    active: '@profileActive@'

############################## micro-gateway start ##############################
micro-gateway:
  # 是否启用ansi控制台输出有颜色的字体
  enable-ansi: true
  # AOP配置
  aop:
    log:
      # 是否启用
      enabled: true
      # 1.请求和响应分开，按照执行顺序打印
      # 2.ThreadLocal线程绑定，方法执行结束时，连续打印请求和响应日志
      # 3.ThreadLocal线程绑定，方法执行结束时，同时打印请求和响应日志
      print-type: 1
      # 请求日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      request-log-format: true
      # 响应日志在控制台是否格式化输出，local环境建议开启，服务器环境设置为false
      response-log-format: true

# 自定义项目信息，Spring Boot Admin展示使用
info:
  project-groupId: '@project.groupId@'
  project-artifactId: '@project.artifactId@'
  project-name: '@project.name@'
  project-finalName: '@project.build.finalName@'
  project-author: ${swagger.contact.name}
  project-description: '@project.description@'
  project-sourceEncoding: '@project.build.sourceEncoding@'
  project-spring-boot-version: '@spring-boot.version@'
  project-mybatis-plus-version: '@mybatis-plus-boot-starter.version@'
  project-version: '@project.version@'
############################## Spring boot admin end ###############################

